#!/usr/bin/env python3
from __future__ import annotations

"""Fresh semantic-strategy distillation bridge for frozen 10105 3H.

Why this exists:
The historical strategy reservoir was generated by the historical V1 Advantage
sequence. The previous AveragePolicy semantic continuation therefore asked a
semantic model to fit stale V1 strategy targets and correctly failed to show a
semantic benefit.

This gate instead:
1) freezes the already-passed eight-member 1600-step V1+semantic Advantage
   shadow;
2) generates fresh 3H sampled trajectories under its raw-Advantage ensemble;
3) records the resulting contemporaneous sigma as fresh strategy targets;
4) splits by whole episodes into train/holdout;
5) adapts two AveragePolicy arms from the exact finalized 10105 policy:
      A) V1 control
      B) V1 + the same 30 general semantic features
   with exact shared minibatches and copied Adam history;
6) compares holdout strategy CE/TV and the high-card/no-draw ALL_IN subgroup.

No CFR Advantage targets are generated, no checkpoint is mutated, and nothing
is promoted to production.
"""

import argparse, copy, hashlib, json, math, random, statistics, sys, time
from pathlib import Path
import numpy as np
import torch

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/"python"))
sys.path.insert(0,str(ROOT/"tools"))

from spincore.deepcrusher_benchmark import SPINCORE_POLICY_ID, ExternalExactAction, OfflineHeadToHeadEngine
from spincore.deepcrusher_policy import DeepCrusherR8Policy
from spincore.decision_sanity import sanity_flags
from spincore.legacy_scenario import LegacyScenarioConfig, LegacyScenarioSampler
from spincore.lean_action_scope import FIRST_RELEASE_ACTION_SPEC
from spincore.lean_solver_actions import LeanSolverState, apply_lean, resolve_lean_exact
from spincore.r7_5_action_cfr import ActionStrategySample, legal_mask, sample_action
from spincore.r7_5_action_contract import NAME_BY_SLOT
from spincore.solver import SolverLibrary
from spincore_nn.action_models import collate_action_observations, make_policy_action_model
from spincore_nn.lean_batch import vectorized_batch
from spincore_nn.training import train_step

from run_3h_v1_semantic_shadow_10105 import (
    V1SemanticAdvantageNet,
    semantic_vector,
)
from audit_3h_average_policy_semantic_continuation_10105 import (
    SEM_DIM,
    build_semantic_from_v1,
    clone_optimizer_state_v1_to_semantic,
    semantic_vector_from_obs,
)

EXPECTED_SHA="f2058cae8a1b194e08295f1b726b43432544d668c86a4c3a4c9ee8724963faa0"
ADV_SCHEMA="SPINCORE_3H_V1_SEMANTIC_SHADOW_MODELS_V1"
REPRESENTATION="C0_V1_FROZEN_CONTROL"
DOMAIN="THREE_HANDED"
ALL_IN=9
MASTER_SEED=20260926 ^ 0xF235A
TRAIN_SEED=20260926 ^ 0xD157111
MILESTONES=(0,500,1000,2000,4000)


def sha256(path):
    h=hashlib.sha256()
    with Path(path).open("rb") as f:
        for b in iter(lambda:f.read(8*1024*1024),b""):h.update(b)
    return h.hexdigest()


def mix64(*values):
    x=0x9E3779B97F4A7C15;mask=(1<<64)-1
    for value in values:
        y=int(value)&mask
        x^=(y+0x9E3779B97F4A7C15+((x<<6)&mask)+(x>>2))&mask
        x&=mask
    return x


def load_semantic_advantage(state):
    m=V1SemanticAdvantageNet()
    m.load_state_dict(state);m.eval()
    return m


def semantic_sigma(models,obs,legal):
    b=collate_action_observations(REPRESENTATION,[obs],[legal_mask(legal)],device="cpu")
    class S: pass
    s=S();s.observation=obs
    sv=semantic_vector(s)
    sb=dict(b);sb["semantic"]=torch.tensor([sv],dtype=torch.float32)
    with torch.no_grad():
        raw=torch.stack([m(sb)[0] for m in models],dim=0).mean(dim=0).cpu().tolist()
    positive=sum(max(0.0,float(raw[a])) for a in legal)
    out=[0.0]*10
    if positive<=0:
        for a in legal:out[a]=1.0/len(legal)
    else:
        for a in legal:out[a]=max(0.0,float(raw[a]))/positive
    return tuple(out)


def collect_fresh(solver,models,episodes):
    sampler=LegacyScenarioSampler(seed=MASTER_SEED,config=LegacyScenarioConfig())
    action_rng=random.Random(MASTER_SEED^0xAC710)
    train=[];hold=[]
    stats={"episodes":episodes,"train_episodes":0,"holdout_episodes":0,"decisions":0}
    for ep_idx in range(int(episodes)):
        ep=sampler.sample_episode(force_domain=DOMAIN)
        raw=solver.create(ep,int(mix64(MASTER_SEED,ep_idx,0xDEC4)))
        state=LeanSolverState(raw)
        dst=hold if ep_idx%5==0 else train
        if ep_idx%5==0:stats["holdout_episodes"]+=1
        else:stats["train_episodes"]+=1
        try:
            while not state.terminal:
                street=int(state.inner.neural_bytes_v2()[112])
                active=FIRST_RELEASE_ACTION_SPEC.active_mask(street)
                legal=tuple(int(x) for x in state.inner.universal_legal_actions(active))
                obs=state.neural_bytes()
                sigma=semantic_sigma(models,obs,legal)
                dst.append(ActionStrategySample(
                    observation=obs,
                    legal=legal_mask(legal),
                    target=tuple(float(x) for x in sigma),
                    weight=1.0,
                    iteration=10106,
                ))
                stats["decisions"]+=1
                action=sample_action(sigma,legal,action_rng)
                apply_lean(state.inner,active,action)
        finally:
            state.close()
        if (ep_idx+1)%500==0:
            print(f"FRESH_STRATEGY_EPISODES {ep_idx+1}/{episodes} decisions={stats['decisions']}",flush=True)
    stats["train_samples"]=len(train);stats["holdout_samples"]=len(hold)
    return train,hold,stats


def hcdn(obs):
    # Reuse the corrected semantic helper contract.
    from audit_3h_semantic_sidecar_attribution_10105 import decode_obs, private_semantics
    hole,board,_n,_c=decode_obs(obs)
    return bool(private_semantics(hole,board)["high_card_no_draw"])


def metrics(v1,sem,samples,batch_size=4096):
    ce_v=[];ce_s=[];tv_v=[];tv_s=[];weights=[]
    hc_t=[];hc_v=[];hc_s=[];hc_w=[]
    v1.eval();sem.eval()
    for start in range(0,len(samples),batch_size):
        chunk=samples[start:start+batch_size]
        b,t,w=vectorized_batch(chunk,"cpu")
        sb=dict(b);sb["semantic"]=torch.tensor(
            np.asarray([semantic_vector_from_obs(s.observation) for s in chunk],dtype=np.float32)
        )
        with torch.no_grad():
            lv=v1(b).masked_fill(~b["legal"],-1e9)
            ls=sem(sb).masked_fill(~b["legal"],-1e9)
            pv=torch.softmax(lv,dim=-1).cpu();ps=torch.softmax(ls,dim=-1).cpu()
            logv=torch.log_softmax(lv,dim=-1).cpu();logs=torch.log_softmax(ls,dim=-1).cpu()
        tc=t.cpu();legal=b["legal"].cpu();ww=w.cpu()
        for i,s in enumerate(chunk):
            la=[a for a,x in enumerate(legal[i].tolist()) if bool(x)]
            tgt=[float(x) for x in tc[i].tolist()]
            pvi=[float(x) for x in pv[i].tolist()];psi=[float(x) for x in ps[i].tolist()]
            ce_v.append(-sum(tgt[a]*float(logv[i,a]) for a in la))
            ce_s.append(-sum(tgt[a]*float(logs[i,a]) for a in la))
            tv_v.append(0.5*sum(abs(tgt[a]-pvi[a]) for a in la))
            tv_s.append(0.5*sum(abs(tgt[a]-psi[a]) for a in la))
            weights.append(float(ww[i]))
            if ALL_IN in la and hcdn(s.observation):
                hc_t.append(tgt[ALL_IN]);hc_v.append(pvi[ALL_IN]);hc_s.append(psi[ALL_IN]);hc_w.append(float(ww[i]))
    def wm(vals,ws):return sum(v*w for v,w in zip(vals,ws))/sum(ws) if ws else None
    target=wm(hc_t,hc_w);vpred=wm(hc_v,hc_w);spred=wm(hc_s,hc_w)
    return {
        "count":len(samples),
        "v1_weighted_ce":wm(ce_v,weights),
        "semantic_weighted_ce":wm(ce_s,weights),
        "v1_weighted_tv":wm(tv_v,weights),
        "semantic_weighted_tv":wm(tv_s,weights),
        "high_card_no_draw_allin":{
            "count":len(hc_t),"target_weighted_mean":target,
            "v1_weighted_mean":vpred,"semantic_weighted_mean":spred,
            "v1_abs_bias":abs(vpred-target) if target is not None else None,
            "semantic_abs_bias":abs(spred-target) if target is not None else None,
        },
    }


def named(values,legal):
    return {str(NAME_BY_SLOT.get(int(a),f"SLOT_{int(a)}")):float(values[a]) for a in legal}


class CapturePolicy:
    policy_id=SPINCORE_POLICY_ID
    def __init__(self,agent):self.agent=agent;self.last={}
    def choose_exact(self,state,*,seat,rng):
        active,legal,probs=self.agent.distribution(state);domain=self.agent.domain_for_state(state)
        x=rng.random();cum=0.0;slot=int(legal[-1])
        for a in legal:
            cum+=float(probs[a])
            if x<cum:slot=int(a);break
        at,amt=resolve_lean_exact(state,active,slot)
        self.last[int(seat)]={"domain":domain,"observation_hex":state.neural_bytes().hex() if domain==DOMAIN else None,"legal_slots":[int(a) for a in legal] if domain==DOMAIN else None}
        return ExternalExactAction(int(at),int(amt))
    def decision_metadata(self,*,seat):
        x=self.last.get(int(seat));return None if x is None else dict(x)


def exact_probs(v1,sem,obs,legal):
    b=collate_action_observations(REPRESENTATION,[obs],[legal_mask(legal)],device="cpu")
    sb=dict(b);sb["semantic"]=torch.tensor([semantic_vector_from_obs(obs)],dtype=torch.float32)
    with torch.no_grad():
        pv=torch.softmax(v1(b).masked_fill(~b["legal"],-1e9),dim=-1)[0].cpu().tolist()
        ps=torch.softmax(sem(sb).masked_fill(~b["legal"],-1e9),dim=-1)[0].cpu().tolist()
    return named(pv,legal),named(ps,legal)


def dc1(solver,bundle,v1,sem,scenarios):
    from spincore.lean_hybrid_deployment_agent import LeanHybridDeploymentAgent
    agent=LeanHybridDeploymentAgent.from_bundle(bundle,device="cpu",seed=0)
    spin=CapturePolicy(agent);deep=DeepCrusherR8Policy.from_repository(ROOT)
    sampler=LegacyScenarioSampler(seed=20260923^0x5CE0A710,config=LegacyScenarioConfig())
    traces=[];games=0
    for i in range(int(scenarios)):
        ep=sampler.sample_episode()
        eng=OfflineHeadToHeadEngine(solver,spincore_policy=spin,deepcrusher_policy=deep,master_seed=20260923,max_decisions=200,decision_sink=traces.append)
        games+=len(eng.play_balanced_block(ep,deal_seed=int(mix64(20260923,i,0xD34A1)),scenario_index=i))
    high=[];trips=[]
    for tr in traces:
        if tr.policy_id!=SPINCORE_POLICY_ID or tr.domain!=DOMAIN:continue
        d=dict(tr.policy_detail or {});obs=d.get("observation_hex");legal=tuple(int(x) for x in d.get("legal_slots") or ())
        if not obs or not legal:continue
        vp,sp=exact_probs(v1,sem,bytes.fromhex(obs),legal)
        for f in sanity_flags(tr):
            row={"v1":vp,"semantic":sp,"context":f.context}
            if f.code=="POSTFLOP_DEEP_HIGH_CARD_JAM":high.append(row)
            elif f.code=="POSTFLOP_TRIPS_PLUS_FOLD":trips.append(row)
    nodraw=[r for r in high if not bool((r["context"] or {}).get("has_immediate_straight_or_flush_draw"))]
    def summ(rows,action):
        if not rows:return {"count":0}
        return {"count":len(rows),
            "v1_action_probability_mean":statistics.fmean(r["v1"].get(action,0) for r in rows),
            "semantic_action_probability_mean":statistics.fmean(r["semantic"].get(action,0) for r in rows),
            "v1_argmax_count":sum(max(r["v1"],key=r["v1"].get)==action for r in rows),
            "semantic_argmax_count":sum(max(r["semantic"],key=r["semantic"].get)==action for r in rows)}
    return {"balanced_games":games,"trace_decisions":len(traces),
            "high_card_jam_all":summ(high,"ALL_IN"),
            "high_card_jam_no_immediate_draw":summ(nodraw,"ALL_IN"),
            "trips_plus_fold":summ(trips,"FOLD")}


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--checkpoint",type=Path,required=True)
    ap.add_argument("--semantic-advantage-models",type=Path,required=True)
    ap.add_argument("--solver",type=Path,required=True)
    ap.add_argument("--spin-bundle",type=Path,required=True)
    ap.add_argument("--report",type=Path,required=True)
    ap.add_argument("--out-model",type=Path,required=True)
    ap.add_argument("--episodes",type=int,default=4000)
    ap.add_argument("--threads",type=int,default=8)
    ap.add_argument("--max-projected-minutes",type=float,default=60.0)
    args=ap.parse_args();torch.set_num_threads(int(args.threads))

    cp=args.checkpoint.resolve(strict=True)
    if sha256(cp)!=EXPECTED_SHA:raise SystemExit("checkpoint SHA mismatch")
    payload=torch.load(cp,map_location="cpu",weights_only=False)
    d3=(payload.get("domains") or {}).get(DOMAIN) or {};cfg=dict(payload.get("config") or {})

    advp=torch.load(args.semantic_advantage_models.resolve(strict=True),map_location="cpu",weights_only=False)
    if advp.get("schema")!=ADV_SCHEMA or int(advp.get("budget",-1))!=1600:raise SystemExit("wrong semantic Advantage artifact")
    adv_models=[load_semantic_advantage(s) for s in advp["members"]]
    if len(adv_models)!=8:raise SystemExit("expected eight semantic Advantage models")

    solver=SolverLibrary(args.solver.resolve(strict=True))
    train,hold,collection=collect_fresh(solver,adv_models,args.episodes)
    if len(hold)<5000:raise RuntimeError(f"fresh holdout too small: {len(hold)}")

    _,v1=make_policy_action_model(REPRESENTATION,device="cpu",seed=0);v1.load_state_dict(d3["policy"])
    v1opt=torch.optim.Adam(v1.parameters(),lr=float(cfg["learning_rate"]));v1opt.load_state_dict(copy.deepcopy(d3["pol_opt"]))
    sem=build_semantic_from_v1(v1);semopt=torch.optim.Adam(sem.parameters(),lr=float(cfg["learning_rate"]))
    clone_optimizer_state_v1_to_semantic(v1,v1opt,sem,semopt)

    # Exact structural step-0 identity plus bounded float drift.
    sample=train[:min(1024,len(train))];b,_,_=vectorized_batch(sample,"cpu")
    sb=dict(b);sb["semantic"]=torch.tensor(np.asarray([semantic_vector_from_obs(s.observation) for s in sample],dtype=np.float32))
    with torch.no_grad():
        ld=(v1(b)-sem(sb)).abs().max().item()
    if ld>2e-6:raise RuntimeError(f"step0 drift {ld}")

    rng=random.Random(TRAIN_SEED);bs=int(cfg["batch_size"])
    milestones=[];completed=0;t0=time.perf_counter()
    def snap(step):
        m=metrics(v1,sem,hold);m["extra_steps"]=step;milestones.append(m)
        print("FRESH_DISTILL_MILESTONE "+json.dumps(m,sort_keys=True),flush=True)
    snap(0)
    for target_step in MILESTONES[1:]:
        while completed<target_step:
            idx=rng.sample(range(len(train)),min(bs,len(train)));samples=[train[i] for i in idx]
            b,t,w=vectorized_batch(samples,"cpu")
            sb=dict(b);sb["semantic"]=torch.tensor(np.asarray([semantic_vector_from_obs(s.observation) for s in samples],dtype=np.float32))
            train_step(v1,v1opt,b,t,w,"strategy");train_step(sem,semopt,sb,t,w,"strategy")
            completed+=1
            if completed==500:
                projected=(time.perf_counter()-t0)/500*MILESTONES[-1]/60
                print(f"FRESH_DISTILL_PERF_GATE projected_minutes={projected:.3f} limit={args.max_projected_minutes:.3f}",flush=True)
                if projected>args.max_projected_minutes:raise RuntimeError("fresh distillation performance gate")
        snap(completed)

    final=milestones[-1];hc=final["high_card_no_draw_allin"]
    criteria={
        "semantic_weighted_ce_better_than_v1":final["semantic_weighted_ce"]<final["v1_weighted_ce"],
        "semantic_weighted_tv_better_than_v1":final["semantic_weighted_tv"]<final["v1_weighted_tv"],
        "semantic_high_card_abs_bias_at_least_25pct_better":hc["semantic_abs_bias"]<=0.75*hc["v1_abs_bias"] if hc["v1_abs_bias"]>0 else False,
        "semantic_ce_improves_from_step0":final["semantic_weighted_ce"]<milestones[0]["semantic_weighted_ce"],
    }
    passed=all(criteria.values())
    dcrep=dc1(solver,args.spin_bundle.resolve(strict=True),v1,sem,200)

    torch.save({"schema":"SPINCORE_3H_FRESH_SEMANTIC_STRATEGY_DISTILL_MODEL_V1","checkpoint_sha256":EXPECTED_SHA,
                "extra_steps":4000,"model_state":{k:v.detach().cpu() for k,v in sem.state_dict().items()},
                "production_status":"DIAGNOSTIC_ONLY_NOT_PROMOTED"},args.out_model)

    report={"schema":"SPINCORE_3H_FRESH_SEMANTIC_STRATEGY_DISTILL_AUDIT_V1",
            "scope":"DIAGNOSTIC_ONLY_FRESH_SEMANTIC_STRATEGY_TARGETS_NO_CFR_ADVANTAGE_UPDATE",
            "checkpoint_sha256":EXPECTED_SHA,"semantic_advantage_schema":ADV_SCHEMA,
            "collection":collection,"milestones":milestones,"final_holdout":final,"dc1":dcrep,
            "precommitted_criteria":criteria,"fresh_semantic_strategy_distill_pass":passed,
            "interpretation":"PASS means the AveragePolicy can distill fresh strategy targets generated by the semantic Advantage candidate better when given the same general semantic representation. This isolates stale historical strategy targets from representation capacity. PASS still does not authorize production; it authorizes one bounded paired online semantic-CFR continuation."}
    args.report.parent.mkdir(parents=True,exist_ok=True)
    args.report.write_text(json.dumps(report,indent=2,sort_keys=True)+"\n",encoding="utf-8")
    print("criteria="+json.dumps(criteria,sort_keys=True))
    print(f"fresh_semantic_strategy_distill_pass={passed}")
    print(f"report={args.report.resolve()}")
    print("3H_FRESH_SEMANTIC_STRATEGY_DISTILL_RUN_PASS")
    return 0
if __name__=="__main__":raise SystemExit(main())
