#!/usr/bin/env python3
from __future__ import annotations

"""Corrected Jammer-facing overlay using ONE common Jammer-conditioned reference.

V1 compared Stage A and Stage B to stage-specific self-play posteriors. That is
not the correct benchmark reference for states generated by the fixed JAMMER:
JAMMER's action rule depends only on the legal action set, never on hole cards.
Conditioning on an observed Jammer shove therefore does not reweight opponent
hands. For the same observable state and hero cards, Stage A and Stage B must be
compared to the same uniform-opponent-hand / uniform-future-board conditional
reference.

This read-only V2 reconstructs the same class of actual forensic first-divergence
states and reports:
  * Stage-A/B AveragePolicy error to the SAME common reference;
  * Stage-A/B current Advantage-induced policy error to the SAME reference;
  * K1 vs K4 board-only estimator error to that same reference;
  * action-mass shifts in FOLD / CHECK_CALL / ALL_IN.

At these anchors the opponent is already all-in, so fixed-deal ACTION VALUES
are independent of any future opponent behavior policy. The raw Deep-CFR
Advantage target is nevertheless stage-dependent by an additive scalar because
it is centered by that stage's current traverser policy value:
    target[a] = Q[a] - sum_b sigma[b] Q[b].
V2.1 therefore compares a canonical zero-mean-over-legal-actions gauge. This
preserves every action-value gap while removing the policy-dependent scalar
baseline. Stage-A and Stage-B canonicalized fixed-deal targets must match.
"""

import argparse
import json
from pathlib import Path
import random
import statistics
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))
sys.path.insert(0, str(ROOT / "tools"))

import torch

import audit_lt2_hu_preflop_conditional_resampling as cond
import audit_lt2_jammer_facing_allin_target_overlay as v1
from audit_lt2_checkpoint_fit import _lean_rm_policy_tensor, _selftest_lean_rm_policy_tensor
from audit_lt2_hu_preflop_target_estimator_budget import _mean_ci, _policy_metrics
from audit_lt2_repeated_target_variance import _capture_root_target

FORENSIC_SEEDS = v1.FORENSIC_SEEDS
REPRESENTATION = v1.REPRESENTATION
CHIP_SCALE = v1.CHIP_SCALE


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--solver", type=Path, default=ROOT / "build/libspincore_solver_c.so")
    p.add_argument("--stage-a", type=Path, required=True)
    p.add_argument("--stage-b", type=Path, required=True)
    p.add_argument("--scenarios-per-seed", type=int, default=5000)
    p.add_argument("--anchors-per-seed", type=int, default=4)
    p.add_argument("--reference-hands", type=int, default=32)
    p.add_argument("--reference-boards-per-hand", type=int, default=8)
    p.add_argument("--candidate-hands", type=int, default=16)
    p.add_argument("--candidate-boards-per-hand", type=int, default=4)
    p.add_argument("--threads", type=int, default=8)
    p.add_argument("--report", type=Path, required=True)
    return p.parse_args()


def _uniform_hand_indices(hands: list[tuple[int, int]], k: int, *, seed: int) -> list[int]:
    probs = [1.0 / float(len(hands))] * len(hands)
    return cond._stratified_hand_indices(probs, int(k), seed=int(seed))


def _capture_fixed_deal(
    *,
    solver,
    stage: v1.StageModels,
    anchor: dict[str, Any],
    opponent_hand: tuple[int, int],
    board: tuple[int, int, int, int, int],
    rng_seed: int,
) -> tuple[torch.Tensor, int]:
    holes = cond._holes_for(
        anchor["episode"],
        hero_seat=int(anchor["actor"]),
        hero_cards=tuple(anchor["hero_cards"]),
        opponent_seat=int(anchor["opponent_seat"]),
        opponent_hand=tuple(opponent_hand),
    )
    state, _ = cond._replay_to_anchor(
        solver=solver,
        runtime=stage.runtime,
        episode=anchor["episode"],
        holes=holes,
        board=board,
        action_path=tuple(anchor["action_path"]),
        target_actor=int(anchor["actor"]),
        target_observation=anchor["observation"],
        target_legal_mask=tuple(anchor["legal_mask"]),
        compute_opponent_log_reach=False,
    )
    try:
        sample, nodes = _capture_root_target(
            stage.runtime,
            state,
            iteration=int(stage.completed_iteration) + 1,
            exact_level=0,
            rng_seed=int(rng_seed),
        )
    finally:
        state.close()
    if sample.observation != anchor["observation"]:
        raise RuntimeError("V2 target observation drift")
    return torch.tensor(sample.target, dtype=torch.float32), int(nodes)


def _canonicalize_target(
    target: torch.Tensor,
    legal: torch.Tensor,
) -> torch.Tensor:
    """Remove the arbitrary/current-policy scalar baseline from Advantage labels.

    At a traverser node the collector stores Q(a) - V_sigma. Different Stage-A/B
    sigma therefore shifts every legal action by the same scalar even when all
    Q(a) values are identical. Subtracting the equal-weight legal-action mean
    chooses one common gauge: Q(a) - mean_legal Q.
    """
    out = target.detach().clone().float()
    legal_values = out[legal]
    if int(legal_values.numel()) <= 0:
        raise RuntimeError("canonical target requires at least one legal action")
    out[legal] = legal_values - legal_values.mean()
    out[~legal] = 0.0
    return out


def _assert_same_action_gaps(
    a_raw: torch.Tensor,
    b_raw: torch.Tensor,
    legal: torch.Tensor,
    *,
    atol: float = 1e-7,
) -> tuple[torch.Tensor, torch.Tensor, float, float]:
    """Assert Stage A/B differ only by the expected common scalar baseline."""
    a = _canonicalize_target(a_raw, legal)
    b = _canonicalize_target(b_raw, legal)
    centered_delta = float(torch.max(torch.abs(a - b)).item())
    if centered_delta > float(atol):
        raise RuntimeError(
            "Stage-A/B fixed-deal ACTION GAPS differ after opponent already all-in: "
            f"canonical_max_abs={centered_delta}"
        )

    raw_diff = (a_raw - b_raw)[legal]
    nonconstant_range = float((raw_diff.max() - raw_diff.min()).item())
    if nonconstant_range > float(atol):
        raise RuntimeError(
            "Stage-A/B raw target difference is not a common scalar baseline: "
            f"range={nonconstant_range}"
        )
    raw_offset = float(raw_diff.mean().item())
    return a, b, centered_delta, raw_offset


def _policy_against_reference(
    policy: torch.Tensor,
    reference_target: torch.Tensor,
    legal: torch.Tensor,
) -> dict[str, Any]:
    ref_policy = _lean_rm_policy_tensor(
        reference_target.unsqueeze(0), legal.unsqueeze(0)
    )[0]
    tv = float((0.5 * torch.abs(policy - ref_policy).sum()).item())
    policy_value = float((policy * reference_target).sum().item())
    ref_value = float((ref_policy * reference_target).sum().item())
    best = float(reference_target.masked_fill(~legal, float("-inf")).max().item())
    return {
        "tv_to_reference": tv,
        "argmax_agreement": bool(
            int(policy.masked_fill(~legal, -1.0).argmax().item())
            == int(ref_policy.masked_fill(~legal, -1.0).argmax().item())
        ),
        "signed_reference_policy_minus_policy_value_gap_chips": float(
            (ref_value - policy_value) * CHIP_SCALE
        ),
        "policy_regret_to_reference_best_action_chips": float(
            max(0.0, best - policy_value) * CHIP_SCALE
        ),
        "action_mass": [float(x) for x in policy.tolist()],
    }


def _candidate_metrics(rows: list[dict[str, Any]]) -> dict[str, float]:
    return {
        "target_mse_to_reference": float(
            statistics.fmean(r["target_mse_to_reference"] for r in rows)
        ),
        "policy_tv_to_reference": float(
            statistics.fmean(r["policy_tv_to_reference"] for r in rows)
        ),
        "argmax_agreement_rate": float(
            statistics.fmean(1.0 if r["argmax_agreement"] else 0.0 for r in rows)
        ),
        "branch_mismatch_rate": float(
            statistics.fmean(1.0 if r["branch_mismatch"] else 0.0 for r in rows)
        ),
        "signed_reference_policy_minus_candidate_policy_value_gap_chips": float(
            statistics.fmean(
                r["signed_reference_policy_minus_candidate_policy_value_gap_chips"]
                for r in rows
            )
        ),
        "candidate_policy_regret_to_reference_best_action_chips": float(
            statistics.fmean(
                r["candidate_policy_regret_to_reference_best_action_chips"]
                for r in rows
            )
        ),
        "nodes": float(statistics.fmean(r["nodes"] for r in rows)),
    }


def _common_reference_and_candidates(
    *,
    solver,
    stage_a: v1.StageModels,
    stage_b: v1.StageModels,
    anchor: dict[str, Any],
    ref_hands: int,
    ref_boards: int,
    cand_hands: int,
    cand_boards: int,
) -> dict[str, Any]:
    hero_cards = tuple(anchor["hero_cards"])
    hands = cond._ordered_hands(hero_cards)
    legal = torch.tensor(anchor["legal_mask"], dtype=torch.bool)

    ref_idx = _uniform_hand_indices(
        hands,
        int(ref_hands),
        seed=v1._mix64(anchor["anchor_index"], 0xC0A0A0, 0xA11CE),
    )
    ref_targets: list[torch.Tensor] = []
    ref_nodes = []
    max_stage_canonical_delta = 0.0
    max_raw_stage_offset_abs = 0.0

    for hpos, hidx in enumerate(ref_idx):
        hand = hands[int(hidx)]
        for bpos in range(int(ref_boards)):
            board_rng = random.Random(
                v1._mix64(anchor["anchor_index"], hpos, bpos, 0xB0A2D)
            )
            board = cond._board_for(hero_cards, hand, rng=board_rng)
            rng_seed = v1._mix64(anchor["anchor_index"], hpos, bpos, 0x7A2E7)
            ta, na = _capture_fixed_deal(
                solver=solver,
                stage=stage_a,
                anchor=anchor,
                opponent_hand=hand,
                board=board,
                rng_seed=rng_seed,
            )
            tb, nb = _capture_fixed_deal(
                solver=solver,
                stage=stage_b,
                anchor=anchor,
                opponent_hand=hand,
                board=board,
                rng_seed=rng_seed,
            )
            ca, cb, canonical_delta, raw_offset = _assert_same_action_gaps(
                ta, tb, legal
            )
            max_stage_canonical_delta = max(
                max_stage_canonical_delta,
                float(canonical_delta),
            )
            max_raw_stage_offset_abs = max(
                max_raw_stage_offset_abs,
                abs(float(raw_offset)),
            )
            ref_targets.append(0.5 * (ca + cb))
            ref_nodes.append((int(na), int(nb)))

    reference_target = torch.stack(ref_targets).mean(dim=0)
    reference_policy = _lean_rm_policy_tensor(
        reference_target.unsqueeze(0), legal.unsqueeze(0)
    )[0]

    cand_idx = _uniform_hand_indices(
        hands,
        int(cand_hands),
        seed=v1._mix64(anchor["anchor_index"], 0xC4AD, 0x1AD3F),
    )
    k1_rows = []
    k4_rows = []
    for hpos, hidx in enumerate(cand_idx):
        hand = hands[int(hidx)]
        board_targets = []
        nodes = []
        for bpos in range(int(cand_boards)):
            board_rng = random.Random(
                v1._mix64(anchor["anchor_index"], hpos, bpos, 0xCA4D)
            )
            board = cond._board_for(hero_cards, hand, rng=board_rng)
            target_raw, node_count = _capture_fixed_deal(
                solver=solver,
                stage=stage_a,
                anchor=anchor,
                opponent_hand=hand,
                board=board,
                rng_seed=v1._mix64(anchor["anchor_index"], hpos, bpos, 0xE571),
            )
            board_targets.append(_canonicalize_target(target_raw, legal))
            nodes.append(int(node_count))

        k1 = board_targets[0]
        k4 = torch.stack(board_targets[:4]).mean(dim=0)
        m1 = _policy_metrics(k1, reference_target, legal)
        m4 = _policy_metrics(k4, reference_target, legal)
        m1["nodes"] = int(nodes[0])
        m4["nodes"] = int(sum(nodes[:4]))
        k1_rows.append(m1)
        k4_rows.append(m4)

    avg_a = torch.tensor(anchor["avg_a_probs"], dtype=torch.float32)
    avg_b = torch.tensor(anchor["avg_b_probs"], dtype=torch.float32)

    raw_a = cond._model_raw(
        stage_a.runtime, anchor["observation"], tuple(anchor["legal_mask"])
    )
    raw_b = cond._model_raw(
        stage_b.runtime, anchor["observation"], tuple(anchor["legal_mask"])
    )
    adv_a = _lean_rm_policy_tensor(raw_a.unsqueeze(0), legal.unsqueeze(0))[0]
    adv_b = _lean_rm_policy_tensor(raw_b.unsqueeze(0), legal.unsqueeze(0))[0]

    return {
        "reference": {
            "opponent_hand_posterior": "UNIFORM_BECAUSE_JAMMER_ACTIONS_ARE_HAND_INDEPENDENT",
            "hands": int(ref_hands),
            "boards_per_hand": int(ref_boards),
            "deals": len(ref_targets),
            "target": [float(x) for x in reference_target.tolist()],
            "policy": [float(x) for x in reference_policy.tolist()],
            "mean_nodes_stage_a": float(
                statistics.fmean(x[0] for x in ref_nodes)
            ),
            "mean_nodes_stage_b": float(
                statistics.fmean(x[1] for x in ref_nodes)
            ),
            "max_stage_a_b_fixed_deal_canonical_target_abs_delta": float(
                max_stage_canonical_delta
            ),
            "max_stage_a_b_raw_target_common_offset_abs": float(
                max_raw_stage_offset_abs
            ),
        },
        "stage_a": {
            "average_policy": _policy_against_reference(
                avg_a, reference_target, legal
            ),
            "advantage_policy": {
                **_policy_metrics(raw_a, reference_target, legal),
                "action_mass": [float(x) for x in adv_a.tolist()],
            },
        },
        "stage_b": {
            "average_policy": _policy_against_reference(
                avg_b, reference_target, legal
            ),
            "advantage_policy": {
                **_policy_metrics(raw_b, reference_target, legal),
                "action_mass": [float(x) for x in adv_b.tolist()],
            },
        },
        "candidate_k1": _candidate_metrics(k1_rows),
        "candidate_k4": _candidate_metrics(k4_rows),
    }


def _paired(rows: list[dict[str, Any]], getter) -> dict[str, float | int]:
    return _mean_ci([float(getter(r)) for r in rows])


def _aggregate(rows: list[dict[str, Any]]) -> dict[str, Any]:
    out: dict[str, Any] = {
        "n": len(rows),
        "forensic_delta_b_minus_a": _paired(
            rows, lambda r: r["forensic_delta_b_minus_a"]
        ),
        "sampled_transition_counts": {},
    }
    trans: dict[str, int] = {}
    for r in rows:
        key = f"{r['a_slot']}->{r['b_slot']}"
        trans[key] = trans.get(key, 0) + 1
    out["sampled_transition_counts"] = dict(
        sorted(trans.items(), key=lambda kv: (-kv[1], kv[0]))
    )

    for stage_key in ("stage_a", "stage_b"):
        out[stage_key] = {}
        for model_key in ("average_policy", "advantage_policy"):
            out[stage_key][model_key] = {
                "tv_to_reference": _paired(
                    rows,
                    lambda r, sk=stage_key, mk=model_key:
                    r[sk][mk]["tv_to_reference"]
                    if mk == "average_policy"
                    else r[sk][mk]["policy_tv_to_reference"],
                ),
                "regret_chips": _paired(
                    rows,
                    lambda r, sk=stage_key, mk=model_key:
                    r[sk][mk]["policy_regret_to_reference_best_action_chips"]
                    if mk == "average_policy"
                    else r[sk][mk]["candidate_policy_regret_to_reference_best_action_chips"],
                ),
            }

    out["stage_b_minus_a"] = {
        "average_policy_tv": _paired(
            rows,
            lambda r:
            r["stage_b"]["average_policy"]["tv_to_reference"]
            - r["stage_a"]["average_policy"]["tv_to_reference"],
        ),
        "average_policy_regret_chips": _paired(
            rows,
            lambda r:
            r["stage_b"]["average_policy"][
                "policy_regret_to_reference_best_action_chips"
            ]
            - r["stage_a"]["average_policy"][
                "policy_regret_to_reference_best_action_chips"
            ],
        ),
        "advantage_policy_tv": _paired(
            rows,
            lambda r:
            r["stage_b"]["advantage_policy"]["policy_tv_to_reference"]
            - r["stage_a"]["advantage_policy"]["policy_tv_to_reference"],
        ),
        "advantage_policy_regret_chips": _paired(
            rows,
            lambda r:
            r["stage_b"]["advantage_policy"][
                "candidate_policy_regret_to_reference_best_action_chips"
            ]
            - r["stage_a"]["advantage_policy"][
                "candidate_policy_regret_to_reference_best_action_chips"
            ],
        ),
    }

    out["candidate_k1"] = {
        "target_mse_to_reference": _paired(
            rows, lambda r: r["candidate_k1"]["target_mse_to_reference"]
        ),
        "policy_tv_to_reference": _paired(
            rows, lambda r: r["candidate_k1"]["policy_tv_to_reference"]
        ),
        "regret_chips": _paired(
            rows,
            lambda r: r["candidate_k1"][
                "candidate_policy_regret_to_reference_best_action_chips"
            ],
        ),
    }
    out["candidate_k4"] = {
        "target_mse_to_reference": _paired(
            rows, lambda r: r["candidate_k4"]["target_mse_to_reference"]
        ),
        "policy_tv_to_reference": _paired(
            rows, lambda r: r["candidate_k4"]["policy_tv_to_reference"]
        ),
        "regret_chips": _paired(
            rows,
            lambda r: r["candidate_k4"][
                "candidate_policy_regret_to_reference_best_action_chips"
            ],
        ),
    }
    out["k4_minus_k1"] = {
        "target_mse_to_reference": _paired(
            rows,
            lambda r:
            r["candidate_k4"]["target_mse_to_reference"]
            - r["candidate_k1"]["target_mse_to_reference"],
        ),
        "policy_tv_to_reference": _paired(
            rows,
            lambda r:
            r["candidate_k4"]["policy_tv_to_reference"]
            - r["candidate_k1"]["policy_tv_to_reference"],
        ),
        "regret_chips": _paired(
            rows,
            lambda r:
            r["candidate_k4"][
                "candidate_policy_regret_to_reference_best_action_chips"
            ]
            - r["candidate_k1"][
                "candidate_policy_regret_to_reference_best_action_chips"
            ],
        ),
    }

    out["mean_action_mass"] = {}
    for stage_key in ("stage_a", "stage_b"):
        out["mean_action_mass"][stage_key] = {}
        for model_key in ("average_policy", "advantage_policy"):
            masses = {}
            for name, action in (("FOLD", 0), ("CHECK_CALL", 1), ("ALL_IN", 9)):
                vals = []
                for r in rows:
                    vals.append(float(r[stage_key][model_key]["action_mass"][action]))
                masses[name] = float(statistics.fmean(vals))
            out["mean_action_mass"][stage_key][model_key] = masses
    out["mean_action_mass"]["reference"] = {
        "FOLD": float(statistics.fmean(r["reference"]["policy"][0] for r in rows)),
        "CHECK_CALL": float(statistics.fmean(r["reference"]["policy"][1] for r in rows)),
        "ALL_IN": float(statistics.fmean(r["reference"]["policy"][9] for r in rows)),
    }
    out["max_stage_a_b_fixed_deal_canonical_target_abs_delta"] = float(
        max(
            r["reference"]["max_stage_a_b_fixed_deal_canonical_target_abs_delta"]
            for r in rows
        )
    )
    out["max_stage_a_b_raw_target_common_offset_abs"] = float(
        max(
            r["reference"]["max_stage_a_b_raw_target_common_offset_abs"]
            for r in rows
        )
    )
    return out


def main() -> int:
    args = parse_args()
    if args.scenarios_per_seed <= 0 or args.anchors_per_seed <= 0:
        raise SystemExit("positive scenario/anchor counts required")
    if args.reference_hands <= 0 or args.reference_boards_per_hand <= 0:
        raise SystemExit("positive reference design required")
    if args.candidate_hands <= 0 or args.candidate_boards_per_hand < 4:
        raise SystemExit("candidate design requires >=4 boards per hand")
    if args.threads <= 0:
        raise SystemExit("positive thread count required")

    args.report.parent.mkdir(parents=True, exist_ok=True)
    torch.set_num_threads(int(args.threads))
    _selftest_lean_rm_policy_tensor()

    solver_path = args.solver.resolve(strict=True)
    stage_a_snapshot = args.report.parent / "stage_a_hu_models.pt"
    stage_b_snapshot = args.report.parent / "stage_b_hu_models.pt"
    print("Extracting lightweight HU model snapshots...", flush=True)
    meta_a = v1._extract_stage_snapshot(
        args.stage_a.resolve(strict=True), stage_a_snapshot
    )
    meta_b = v1._extract_stage_snapshot(
        args.stage_b.resolve(strict=True), stage_b_snapshot
    )

    from spincore.solver import SolverLibrary
    from spincore.legacy_scenario import LegacyScenarioConfig, LegacyScenarioSampler

    solver = SolverLibrary(solver_path)
    stage_a = v1.StageModels(stage_a_snapshot, solver)
    stage_b = v1.StageModels(stage_b_snapshot, solver)

    selected: list[dict[str, Any]] = []
    candidate_counts = {}
    for seed in FORENSIC_SEEDS:
        candidates = v1._collect_seed_candidates(
            solver=solver,
            stage_a=stage_a,
            stage_b=stage_b,
            seed=int(seed),
            scenarios=int(args.scenarios_per_seed),
        )
        candidate_counts[str(seed)] = len(candidates)
        if len(candidates) < int(args.anchors_per_seed):
            raise RuntimeError(
                f"seed {seed} produced only {len(candidates)} facing-all-in divergences"
            )
        chooser = random.Random(v1._mix64(seed, 0x0A7E21A9))
        indices = sorted(
            chooser.sample(range(len(candidates)), int(args.anchors_per_seed))
        )
        for idx in indices:
            selected.append(candidates[idx])

    for index, anchor in enumerate(selected):
        anchor["anchor_index"] = int(index)

    rows = []
    for index, anchor in enumerate(selected):
        print(
            f"JAMMER_COMMON_REF anchor={index+1}/{len(selected)} "
            f"seed={anchor['seed']} scenario={anchor['scenario_index']} "
            f"transition={anchor['a_slot']}->{anchor['b_slot']}",
            flush=True,
        )
        block = _common_reference_and_candidates(
            solver=solver,
            stage_a=stage_a,
            stage_b=stage_b,
            anchor=anchor,
            ref_hands=int(args.reference_hands),
            ref_boards=int(args.reference_boards_per_hand),
            cand_hands=int(args.candidate_hands),
            cand_boards=int(args.candidate_boards_per_hand),
        )
        rows.append(
            {
                "anchor_index": int(index),
                "seed": int(anchor["seed"]),
                "scenario_index": int(anchor["scenario_index"]),
                "blind": str(anchor["blind"]),
                "actor": int(anchor["actor"]),
                "action_path": list(anchor["action_path"]),
                "a_slot": int(anchor["a_slot"]),
                "b_slot": int(anchor["b_slot"]),
                "forensic_delta_b_minus_a": int(
                    anchor["forensic_delta_b_minus_a"]
                ),
                **block,
            }
        )

    summary = _aggregate(rows)
    if summary["max_stage_a_b_fixed_deal_canonical_target_abs_delta"] > 1e-7:
        raise RuntimeError("common-reference action-gap invariance assertion failed")

    report = {
        "schema": "SPINCORE_LT2_JAMMER_FACING_ALLIN_COMMON_REFERENCE_V2_1",
        "stage_a": {
            "checkpoint": str(args.stage_a.resolve()),
            "completed_iteration": int(meta_a["completed_iteration"]),
        },
        "stage_b": {
            "checkpoint": str(args.stage_b.resolve()),
            "completed_iteration": int(meta_b["completed_iteration"]),
        },
        "method": {
            "read_only": True,
            "training_memory_writes": 0,
            "optimizer_steps": 0,
            "new_training_roots": 0,
            "forensic_seeds": list(FORENSIC_SEEDS),
            "future_holdout_seeds_touched": False,
            "scenarios_per_seed": int(args.scenarios_per_seed),
            "anchors_per_seed": int(args.anchors_per_seed),
            "common_reference": (
                "uniform opponent-hand posterior conditional on hero cards/public "
                "state because fixed JAMMER action probabilities do not depend on "
                "opponent hole cards; uniform future boards"
            ),
            "reference_hands": int(args.reference_hands),
            "reference_boards_per_hand": int(args.reference_boards_per_hand),
            "fixed_deal_stage_action_gap_invariance_asserted": True,
            "canonical_advantage_gauge": (
                "subtract equal-weight mean over legal action targets, yielding "
                "Q(a)-mean_legal(Q); this removes the Stage-specific V_sigma scalar "
                "while preserving every action-value gap"
            ),
            "raw_stage_target_difference_expected": (
                "a common scalar offset because collector target is Q(a)-V_sigma "
                "and Stage A/B have different current traverser policies"
            ),
            "candidate_hands": int(args.candidate_hands),
            "candidate_boards_per_hand": int(args.candidate_boards_per_hand),
            "v1_correction": (
                "V1 used stage-specific self-play posteriors and therefore did not "
                "place Stage A and Stage B against one common Jammer-conditioned "
                "benchmark reference. Initial V2 then incorrectly required raw "
                "Advantage labels to be equal across stages. V2.1 uses the common "
                "Jammer reference and compares action gaps in a canonical gauge."
            ),
            "warning": (
                "selected first-divergence states are forensic design data, not "
                "natural-visitation or GTO estimates"
            ),
        },
        "candidate_counts_by_seed": candidate_counts,
        "summary": summary,
        "rows": rows,
    }
    args.report.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print("=== JAMMER FACING-ALL-IN COMMON-REFERENCE V2 ===")
    print(
        f"anchors={summary['n']} forensic_B-A="
        f"{summary['forensic_delta_b_minus_a']['mean']:+.2f}"
    )
    for stage_key in ("stage_a", "stage_b"):
        x = summary[stage_key]
        print(
            f"{stage_key}: avgTV={x['average_policy']['tv_to_reference']['mean']:.4f} "
            f"advTV={x['advantage_policy']['tv_to_reference']['mean']:.4f}"
        )
    d = summary["stage_b_minus_a"]
    print(
        f"B-A: avgTV={d['average_policy_tv']['mean']:+.4f} "
        f"avgRegret={d['average_policy_regret_chips']['mean']:+.2f} "
        f"advTV={d['advantage_policy_tv']['mean']:+.4f} "
        f"advRegret={d['advantage_policy_regret_chips']['mean']:+.2f}"
    )
    k = summary["k4_minus_k1"]
    print(
        f"K4-K1: mse={k['target_mse_to_reference']['mean']:+.6f} "
        f"tv={k['policy_tv_to_reference']['mean']:+.4f} "
        f"regret={k['regret_chips']['mean']:+.2f}"
    )
    print(
        "max_stage_a_b_fixed_deal_canonical_target_abs_delta="
        f"{summary['max_stage_a_b_fixed_deal_canonical_target_abs_delta']:.3e} "
        "max_raw_common_offset_abs="
        f"{summary['max_stage_a_b_raw_target_common_offset_abs']:.6f}"
    )
    print("LT2_JAMMER_FACING_ALLIN_COMMON_REFERENCE_V2_1_COMPLETE")
    print(f"report={args.report.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
