#!/usr/bin/env python3
from __future__ import annotations

"""Measure decision-level AveragePolicy drift between two finalized SpinCore checkpoints.

States are generated by a checkpoint-independent uniform-legal probe policy, so both
checkpoints are queried on exactly the same solver states. This is a diagnostic of
policy movement, not a strength/exploitability test.
"""

import argparse
from concurrent.futures import ProcessPoolExecutor
import json
import math
import multiprocessing as mp
from pathlib import Path
import random
import statistics
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from spincore.legacy_scenario import LegacyScenarioConfig, LegacyScenarioSampler  # noqa: E402
from spincore.solver import Episode  # noqa: E402

_SOLVER = None
_BEFORE = None
_AFTER = None


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--solver", type=Path, default=ROOT / "build" / "libspincore_solver_c.so")
    p.add_argument("--before", type=Path, required=True)
    p.add_argument("--after", type=Path, required=True)
    p.add_argument("--scenarios", type=int, default=3000)
    p.add_argument("--workers", type=int, default=31)
    p.add_argument("--seed", type=int, default=20260917)
    p.add_argument("--report", type=Path, required=True)
    return p.parse_args()


def _mix64(*values: int) -> int:
    x = 0x9E3779B97F4A7C15
    mask = (1 << 64) - 1
    for value in values:
        y = int(value) & mask
        x ^= (y + 0x9E3779B97F4A7C15 + ((x << 6) & mask) + (x >> 2)) & mask
        x &= mask
    return x


def _init_worker(solver_path: str, before_path: str, after_path: str) -> None:
    global _SOLVER, _BEFORE, _AFTER
    import os

    os.environ["OMP_NUM_THREADS"] = "1"
    os.environ["MKL_NUM_THREADS"] = "1"
    os.environ["SPINCORE_TORCH_THREADS"] = "1"

    import torch

    torch.set_num_threads(1)
    try:
        torch.set_num_interop_threads(1)
    except RuntimeError:
        pass

    from spincore.lean_functional_agent import LeanFunctionalAgent
    from spincore.solver import SolverLibrary

    _SOLVER = SolverLibrary(solver_path)
    _BEFORE = LeanFunctionalAgent.from_checkpoint(before_path, seed=0)
    _AFTER = LeanFunctionalAgent.from_checkpoint(after_path, seed=0)


def _entropy(probs: list[float]) -> float:
    return -sum(p * math.log(p) for p in probs if p > 0.0)


def _worker(task: tuple[int, Episode, int, int]) -> list[dict[str, Any]]:
    index, episode, deal_seed, master_seed = task
    from spincore.lean_functional_agent import _street_from_state
    from spincore.lean_solver_actions import apply_lean

    state = _SOLVER.create(episode, int(deal_seed))
    rng = random.Random(_mix64(master_seed, index, 0xD12F7))
    domain = "TRUE_HEADS_UP" if episode.game_is_hu else "THREE_HANDED"
    blind = f"{episode.small_blind}/{episode.big_blind}"
    rows: list[dict[str, Any]] = []
    decisions = 0
    try:
        while not state.terminal:
            before_mask, before_legal, before_probs = _BEFORE.distribution(state)
            after_mask, after_legal, after_probs = _AFTER.distribution(state)
            if before_mask != after_mask or before_legal != after_legal:
                raise RuntimeError("checkpoint legality/action-mask drift on identical state")

            legal = tuple(int(x) for x in before_legal)
            pa = [float(before_probs[a]) for a in legal]
            pb = [float(after_probs[a]) for a in legal]
            tv = 0.5 * sum(abs(a - b) for a, b in zip(pa, pb))
            arg_a = legal[max(range(len(legal)), key=lambda j: pa[j])]
            arg_b = legal[max(range(len(legal)), key=lambda j: pb[j])]
            street = int(_street_from_state(state))
            rows.append(
                {
                    "domain": domain,
                    "blind": blind,
                    "street": street,
                    "tv": float(tv),
                    "argmax_changed": int(arg_a != arg_b),
                    "entropy_before": float(_entropy(pa)),
                    "entropy_after": float(_entropy(pb)),
                    "maxprob_before": float(max(pa)),
                    "maxprob_after": float(max(pb)),
                }
            )

            slot = legal[rng.randrange(len(legal))]
            apply_lean(state, int(before_mask), int(slot))
            decisions += 1
            if decisions > 200:
                raise RuntimeError("probe trajectory exceeded 200 decisions")
    finally:
        state.close()
    return rows


def _quantile(values: list[float], q: float) -> float:
    if not values:
        return float("nan")
    xs = sorted(values)
    pos = q * (len(xs) - 1)
    lo = int(math.floor(pos))
    hi = int(math.ceil(pos))
    if lo == hi:
        return float(xs[lo])
    frac = pos - lo
    return float(xs[lo] * (1.0 - frac) + xs[hi] * frac)


def _summary(rows: list[dict[str, Any]]) -> dict[str, Any]:
    tvs = [float(r["tv"]) for r in rows]
    n = len(rows)
    return {
        "decisions": n,
        "mean_tv": float(statistics.fmean(tvs)) if n else float("nan"),
        "median_tv": _quantile(tvs, 0.50),
        "p90_tv": _quantile(tvs, 0.90),
        "p95_tv": _quantile(tvs, 0.95),
        "p99_tv": _quantile(tvs, 0.99),
        "fraction_tv_ge_0p01": sum(x >= 0.01 for x in tvs) / n if n else float("nan"),
        "fraction_tv_ge_0p05": sum(x >= 0.05 for x in tvs) / n if n else float("nan"),
        "fraction_tv_ge_0p10": sum(x >= 0.10 for x in tvs) / n if n else float("nan"),
        "argmax_disagreement_rate": sum(int(r["argmax_changed"]) for r in rows) / n if n else float("nan"),
        "mean_entropy_before": float(statistics.fmean(float(r["entropy_before"]) for r in rows)) if n else float("nan"),
        "mean_entropy_after": float(statistics.fmean(float(r["entropy_after"]) for r in rows)) if n else float("nan"),
        "mean_maxprob_before": float(statistics.fmean(float(r["maxprob_before"]) for r in rows)) if n else float("nan"),
        "mean_maxprob_after": float(statistics.fmean(float(r["maxprob_after"]) for r in rows)) if n else float("nan"),
    }


def main() -> int:
    args = parse_args()
    if args.scenarios <= 0 or args.workers <= 0:
        raise SystemExit("scenarios/workers must be positive")
    for path in (args.solver, args.before, args.after):
        if not path.is_file():
            raise SystemExit(f"missing input: {path}")
    if args.workers > 1:
        limit = 512 * 1024 * 1024
        for path in (args.before, args.after):
            if path.stat().st_size > limit:
                raise SystemExit(
                    f"multiprocess policy-drift evaluation requires compact inference checkpoints; "
                    f"refusing large training checkpoint {path} ({path.stat().st_size} bytes). "
                    "Run tools/export_lean_inference_checkpoint.py first."
                )

    sampler = LegacyScenarioSampler(seed=args.seed ^ 0x5CE0A710, config=LegacyScenarioConfig())
    tasks: list[tuple[int, Episode, int, int]] = []
    scenario_domains = {"THREE_HANDED": 0, "TRUE_HEADS_UP": 0}
    for index in range(args.scenarios):
        episode = sampler.sample_episode()
        domain = "TRUE_HEADS_UP" if episode.game_is_hu else "THREE_HANDED"
        scenario_domains[domain] += 1
        tasks.append((index, episode, _mix64(args.seed, index, 0xD34A1), int(args.seed)))

    ctx = mp.get_context("spawn")
    rows: list[dict[str, Any]] = []
    with ProcessPoolExecutor(
        max_workers=min(args.workers, args.scenarios),
        mp_context=ctx,
        initializer=_init_worker,
        initargs=(str(args.solver.resolve()), str(args.before.resolve()), str(args.after.resolve())),
    ) as pool:
        for chunk in pool.map(_worker, tasks, chunksize=1):
            rows.extend(chunk)

    by_domain = {
        domain: _summary([r for r in rows if r["domain"] == domain])
        for domain in ("THREE_HANDED", "TRUE_HEADS_UP")
    }
    by_street = {
        str(street): _summary([r for r in rows if int(r["street"]) == street])
        for street in range(4)
    }
    by_domain_street = {
        f"{domain}:{street}": _summary(
            [r for r in rows if r["domain"] == domain and int(r["street"]) == street]
        )
        for domain in ("THREE_HANDED", "TRUE_HEADS_UP")
        for street in range(4)
    }

    report = {
        "schema": "SPINCORE_POLICY_DRIFT_V1",
        "before": str(args.before.resolve()),
        "after": str(args.after.resolve()),
        "seed": int(args.seed),
        "scenarios": int(args.scenarios),
        "workers": int(min(args.workers, args.scenarios)),
        "probe_policy": "uniform legal; independent of both compared checkpoints",
        "scenario_domains": scenario_domains,
        "overall": _summary(rows),
        "by_domain": by_domain,
        "by_street": by_street,
        "by_domain_street": by_domain_street,
        "warning": "policy movement diagnostic only; not a strength/exploitability test",
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print("=== SpinCore LT2 policy drift ===")
    print(f"scenarios={args.scenarios} decisions={report['overall']['decisions']} seed={args.seed}")
    for key in ("overall",):
        x = report[key]
        print(
            f"{key}: mean_tv={x['mean_tv']:.6f} median_tv={x['median_tv']:.6f} "
            f"p95_tv={x['p95_tv']:.6f} argmax_disagreement={x['argmax_disagreement_rate']:.6f}"
        )
    for domain, x in by_domain.items():
        print(
            f"{domain}: decisions={x['decisions']} mean_tv={x['mean_tv']:.6f} "
            f"p95_tv={x['p95_tv']:.6f} argmax_disagreement={x['argmax_disagreement_rate']:.6f}"
        )
    print(f"POLICY_DRIFT_REPORT={args.report.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
