#include "spincore/betting_engine.hpp"
#include <algorithm>
#include <stdexcept>
namespace spincore {
BettingEngine::BettingEngine(const EpisodeScenario& s,GameTopology t):scenario_(s),topology_(t){for(int i=0;i<3;++i){players_[i].stack=s.state.stacks[i];players_[i].all_in=(players_[i].stack==0);}last_full_raise_size_=s.state.big_blind;post_blind(t.small_blind_seat,s.state.small_blind);post_blind(t.big_blind_seat,s.state.big_blind);current_bet_=std::max(players_[t.small_blind_seat].street_commitment,players_[t.big_blind_seat].street_commitment);actor_=t.first_preflop;while(actor_>=0&&!needs_action(actor_))actor_=next_actor_from(actor_);if(actor_<0)street_complete_=true;}
void BettingEngine::post_blind(int seat,int amount){if(seat<0)return;int pot_before=pot();auto&p=players_[(std::size_t)seat];int pay=std::min(p.stack,amount);p.stack-=pay;p.street_commitment+=pay;p.total_commitment+=pay;if(p.stack==0)p.all_in=true;history_.push_back({seat,street_,{ExactActionType::BetTo,p.street_commitment},pay,p.street_commitment,pot(),pot_before,true});}
int BettingEngine::pot() const noexcept{int s=0;for(auto&p:players_)s+=p.total_commitment;return s;}
int BettingEngine::nonfolded_count() const noexcept{int n=0;for(auto&p:players_)if(!p.folded&&(p.stack>0||p.total_commitment>0))++n;return n;}
int BettingEngine::actionable_count() const noexcept{int n=0;for(auto&p:players_)if(!p.folded&&!p.all_in&&p.stack>0)++n;return n;}
bool BettingEngine::needs_action(int seat) const{if(seat<0||seat>2)return false;auto&p=players_[(std::size_t)seat];return !p.folded&&!p.all_in&&p.stack>0&&(!p.acted_since_full_raise||p.street_commitment<current_bet_);}
int BettingEngine::next_actor_from(int seat) const{for(int k=1;k<=3;++k){int q=(seat+k)%3;if(needs_action(q))return q;}return -1;}
LegalActions BettingEngine::legal_actions(int seat) const{LegalActions l{};if(seat!=actor_||street_complete_||hand_over_by_fold_)return l;auto&p=players_[(std::size_t)seat];if(p.folded||p.all_in||p.stack<=0)return l;l.to_call=std::max(0,current_bet_-p.street_commitment);l.max_raise_to=p.street_commitment+p.stack;l.fold=l.to_call>0;l.check=l.to_call==0;l.call=l.to_call>0;l.all_in=p.stack>0;
 bool can_raise=!p.acted_since_full_raise; if(current_bet_==0){l.bet=can_raise&&l.max_raise_to>0;l.min_raise_to=std::min(l.max_raise_to,std::max(scenario_.state.big_blind,last_full_raise_size_));}else{l.min_raise_to=current_bet_+last_full_raise_size_;l.raise=can_raise&&l.max_raise_to>current_bet_&&l.max_raise_to>=l.min_raise_to;}return l;}
void BettingEngine::pay_to(int seat,int target){auto&p=players_[(std::size_t)seat];if(target<p.street_commitment||target>p.street_commitment+p.stack)throw std::invalid_argument("bad target");int pay=target-p.street_commitment;p.stack-=pay;p.street_commitment=target;p.total_commitment+=pay;if(p.stack==0)p.all_in=true;}
ActionEvent BettingEngine::apply(int seat,ExactAction a){auto l=legal_actions(seat);if(seat!=actor_)throw std::invalid_argument("out-of-turn action");int pot_before=pot();auto&p=players_[(std::size_t)seat];int before=p.street_commitment;int old_current=current_bet_;bool full_raise=false;
 switch(a.type){case ExactActionType::Fold:if(!l.fold)throw std::invalid_argument("illegal fold");p.folded=true;p.acted_since_full_raise=true;break;case ExactActionType::Check:if(!l.check)throw std::invalid_argument("illegal check");p.acted_since_full_raise=true;break;case ExactActionType::Call:if(!l.call)throw std::invalid_argument("illegal call");pay_to(seat,std::min(l.max_raise_to,current_bet_));p.acted_since_full_raise=true;break;case ExactActionType::BetTo:if(!l.bet)throw std::invalid_argument("illegal bet");if(a.amount_to<l.min_raise_to||a.amount_to>l.max_raise_to)throw std::invalid_argument("bad bet size");pay_to(seat,a.amount_to);full_raise=true;last_full_raise_size_=a.amount_to;current_bet_=a.amount_to;break;case ExactActionType::RaiseTo:if(!l.raise)throw std::invalid_argument("illegal raise");if(a.amount_to<l.min_raise_to||a.amount_to>l.max_raise_to)throw std::invalid_argument("bad raise size");pay_to(seat,a.amount_to);full_raise=true;last_full_raise_size_=a.amount_to-old_current;current_bet_=a.amount_to;break;case ExactActionType::AllIn:{if(!l.all_in)throw std::invalid_argument("illegal allin");int target=l.max_raise_to;if(target<=current_bet_){pay_to(seat,target);p.acted_since_full_raise=true;}else{int inc=target-current_bet_;pay_to(seat,target);current_bet_=target;if(old_current==0||inc>=last_full_raise_size_){full_raise=true;last_full_raise_size_=old_current==0?target:inc;}}break;}}
 if(full_raise){for(int i=0;i<3;++i)if(i!=seat){auto&q=players_[(std::size_t)i];if(!q.folded&&!q.all_in&&q.stack>0)q.acted_since_full_raise=false;}p.acted_since_full_raise=true;}
 ActionEvent ev{seat,street_,a,p.street_commitment-before,p.street_commitment,pot(),pot_before,false};history_.push_back(ev);update_completion_after_action(seat);return ev;}
void BettingEngine::update_completion_after_action(int acted){if(nonfolded_count()<=1){hand_over_by_fold_=true;street_complete_=true;actor_=-1;return;}bool complete=true;for(int i=0;i<3;++i)if(needs_action(i)){complete=false;break;}if(complete){street_complete_=true;actor_=-1;}else actor_=next_actor_from(acted);if(actor_<0){street_complete_=true;}}
void BettingEngine::advance_street(){if(!street_complete_||hand_over_by_fold_)throw std::logic_error("cannot advance street");if(street_==Street::River)throw std::logic_error("cannot advance past river");street_=static_cast<Street>((int)street_+1);current_bet_=0;last_full_raise_size_=scenario_.state.big_blind;for(auto&p:players_){p.street_commitment=0;p.acted_since_full_raise=false;}street_complete_=false;actor_=topology_.first_postflop;while(actor_>=0&&!needs_action(actor_))actor_=next_actor_from(actor_);if(actor_<0)street_complete_=true;}
}
