#include "spincore/spin_traversal_state.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace spincore { namespace { int clamp_raise_target(int target,const LegalActions&l){return std::min(std::max(target,l.min_raise_to),l.max_raise_to);} }
SpinTraversalState::SpinTraversalState(const EpisodeScenario&s,std::uint64_t seed):scenario_(s),hand_(s,seed){}
CanonicalInfoset SpinTraversalState::infoset()const{if(terminal())throw std::logic_error("terminal state has no infoset");return build_current_actor_infoset(hand_,blind_index());}
NeuralInputV1 SpinTraversalState::neural_input()const{return encode_neural_input_v1(infoset());}
std::vector<AbstractActionSlot> SpinTraversalState::legal_abstract_actions()const{if(terminal())return{};auto info=infoset();std::vector<AbstractActionSlot>o;for(std::uint8_t i=0;i<6;++i)if(info.legal_action_mask[i])o.push_back((AbstractActionSlot)i);return o;}
ExactAction SpinTraversalState::resolve(AbstractActionSlot a)const{if(terminal())throw std::logic_error("cannot resolve terminal");int seat=actor();auto&b=hand_.betting();auto l=b.legal_actions(seat);auto&p=b.players()[(std::size_t)seat];switch(a){case AbstractActionSlot::Fold:if(!l.fold)throw std::invalid_argument("fold illegal");return{ExactActionType::Fold,0};case AbstractActionSlot::CheckCall:if(l.check)return{ExactActionType::Check,0};if(l.call)return{ExactActionType::Call,0};throw std::invalid_argument("check/call illegal");case AbstractActionSlot::AllIn:if(!l.all_in)throw std::invalid_argument("allin illegal");return{ExactActionType::AllIn,0};case AbstractActionSlot::ContextRaise:{if(b.street()!=Street::Preflop||!(l.bet||l.raise))throw std::invalid_argument("context raise illegal");int target=clamp_raise_target(l.min_raise_to,l);if(target>=l.max_raise_to)return{ExactActionType::AllIn,0};return{b.current_bet()==0?ExactActionType::BetTo:ExactActionType::RaiseTo,target};}case AbstractActionSlot::SmallPot:case AbstractActionSlot::LargePot:{if(b.street()==Street::Preflop||!(l.bet||l.raise))throw std::invalid_argument("pot action illegal");double f=a==AbstractActionSlot::SmallPot?0.33:0.75;int pot_after_call=b.pot()+l.to_call;int raw=(int)std::llround(f*pot_after_call);int call_target=p.street_commitment+l.to_call;int target=clamp_raise_target(call_target+std::max(1,raw),l);if(target>=l.max_raise_to)return{ExactActionType::AllIn,0};return{b.current_bet()==0?ExactActionType::BetTo:ExactActionType::RaiseTo,target};}}throw std::invalid_argument("unknown abstract action");}
ActionEvent SpinTraversalState::apply(AbstractActionSlot a){return hand_.apply(actor(),resolve(a));}ActionEvent SpinTraversalState::apply_exact(ExactAction a){if(terminal())throw std::logic_error("terminal");return hand_.apply(actor(),a);}SpinTraversalState SpinTraversalState::child(AbstractActionSlot a)const{auto out=*this;out.apply(a);return out;}
std::array<int,3> SpinTraversalState::terminal_chip_delta()const{if(!terminal())throw std::logic_error("utility before terminal");auto st=hand_.settle();std::array<int,3>d{};for(int i=0;i<3;++i)d[i]=st.final_stacks[i]-scenario_.state.stacks[i];return d;}
std::array<double,3> SpinTraversalState::terminal_icm_delta(const PayoutProfile&p)const{if(!terminal())throw std::logic_error("utility before terminal");return terminal_continuation_delta(scenario_.state,hand_.settle().final_stacks,p);}
}
