#include "spincore/tournament_value.hpp"
#include <algorithm>
#include <cmath>
#include <numeric>
#include <stdexcept>
#include <vector>
namespace spincore {
namespace {
void validate_payout(const PayoutProfile&p){for(double x:p.by_place)if(!std::isfinite(x))throw std::invalid_argument("nonfinite payout");}
int locked_place_for_dead_index(int idx){return 2-idx;}
int left_of_button_order(int seat,int dealer_id){if(seat<0||seat>2||dealer_id<0||dealer_id>2)throw std::invalid_argument("bad seat/dealer for elimination order");return (seat-(dealer_id+1)+6)%3;}
TournamentState after_state(const TournamentState& before,const std::array<int,3>&fs,const PayoutProfile&p,int dealer_id){TournamentState a=before;a.stacks=fs;std::vector<int> newly;for(int i=0;i<3;++i){bool was_dead=false;for(int k=0;k<before.dead_player_count;++k)if(before.dead_players[(std::size_t)k]==i)was_dead=true;if(!was_dead&&fs[(std::size_t)i]==0)newly.push_back(i);}if(newly.size()>2)throw std::logic_error("too many simultaneous eliminations");if(newly.size()==2){int x=newly[0],y=newly[1];int sx=before.stacks[(std::size_t)x],sy=before.stacks[(std::size_t)y];if(sx==sy){int nextidx=before.dead_player_count;int p1=locked_place_for_dead_index(nextidx),p2=locked_place_for_dead_index(nextidx+1);if(std::abs(p.by_place[(std::size_t)p1]-p.by_place[(std::size_t)p2])>1e-12){if(dealer_id<0||dealer_id>2)throw std::runtime_error("ambiguous simultaneous elimination under unequal payouts");int ox=left_of_button_order(x,dealer_id),oy=left_of_button_order(y,dealer_id);if(ox==oy)throw std::logic_error("duplicate elimination position");if(ox<oy)std::swap(newly[0],newly[1]);}}else if(sx>sy)std::swap(newly[0],newly[1]);}
 for(int seat:newly){if(a.dead_player_count>=2)throw std::logic_error("dead history overflow");a.dead_players[(std::size_t)a.dead_player_count++]=seat;}int live=0;for(int x:fs)if(x>0)++live;a.game_is_hu=(live==2);return a;}
}
std::array<double,3> icm_values(const TournamentState&s,const PayoutProfile&p){validate_payout(p);std::array<double,3>v{};std::array<bool,3>dead{};for(int k=0;k<s.dead_player_count;++k){int seat=s.dead_players[(std::size_t)k];if(seat<0||seat>2)throw std::invalid_argument("bad dead history");dead[(std::size_t)seat]=true;int place=locked_place_for_dead_index(k);v[(std::size_t)seat]=p.by_place[(std::size_t)place];}
 std::vector<int>live;double total=0;for(int i=0;i<3;++i)if(!dead[(std::size_t)i]&&s.stacks[(std::size_t)i]>0){live.push_back(i);total+=s.stacks[(std::size_t)i];}if(live.empty())throw std::invalid_argument("no live player");if(live.size()==1){v[(std::size_t)live[0]]=p.by_place[0];return v;}if(live.size()==2){int a=live[0],b=live[1];double pa=s.stacks[(std::size_t)a]/total;v[(std::size_t)a]=pa*p.by_place[0]+(1-pa)*p.by_place[1];v[(std::size_t)b]=(1-pa)*p.by_place[0]+pa*p.by_place[1];return v;}
 for(int i:live){double pi1=s.stacks[(std::size_t)i]/total;double val=pi1*p.by_place[0];for(int j:live)if(j!=i){double pj1=s.stacks[(std::size_t)j]/total;double pi2=pj1*(s.stacks[(std::size_t)i]/(total-s.stacks[(std::size_t)j]));val+=pi2*p.by_place[1];}double p12=0;for(int j:live)if(j!=i)p12+=(s.stacks[(std::size_t)j]/total)*(s.stacks[(std::size_t)i]/(total-s.stacks[(std::size_t)j]));double p3=1.0-pi1-p12;val+=p3*p.by_place[2];v[(std::size_t)i]=val;}return v;}
std::array<double,3> terminal_continuation_delta(const TournamentState&before,const std::array<int,3>&fs,const PayoutProfile&p){auto vb=icm_values(before,p);auto a=after_state(before,fs,p,-1);auto va=icm_values(a,p);std::array<double,3>d{};for(int i=0;i<3;++i)d[(std::size_t)i]=va[(std::size_t)i]-vb[(std::size_t)i];return d;}
std::array<double,3> terminal_continuation_delta(const TournamentState&before,const std::array<int,3>&fs,const PayoutProfile&p,std::int32_t dealer_id){if(dealer_id<0||dealer_id>2)throw std::invalid_argument("invalid dealer for terminal continuation");auto vb=icm_values(before,p);auto a=after_state(before,fs,p,dealer_id);auto va=icm_values(a,p);std::array<double,3>d{};for(int i=0;i<3;++i)d[(std::size_t)i]=va[(std::size_t)i]-vb[(std::size_t)i];return d;}
}
